### PR TITLE
Add command line option to only patch the server

### PR DESCRIPTION
**Pull request by mikroskeem**
Title says it all. ¯\\\_(ツ)\_/¯

### CODE REVIEW

**Comment by aikar** [comment]
This belongs at the paper repo, not here...

**Comment by aikar** [comment]
What is your use case? this already exists even:
https://github.com/PaperMC/Paper/blob/master/paper#L44

just run paper patch

**Comment by Zbob750** [comment]
He doesn't want to constantly compile from source, he wants to be able to download a built paperclip jar file and just have that do the patch then exit.

It does belong here, it is a valid use case.

**Comment by mikroskeem** [comment]
I am behind computer in 10pm (Europe/Tallinn TZ).

Using system property is better option, yes. I didn't think about that. :+1:

> What is your use case?

Look at my project Orion :)

**Comment by mikroskeem** [comment]
Going to open new pull request, because I messed up my repository

**Pull request closed without merging**
