### PR TITLE
Remove Java 6 support

### PR DESCRIPTION
**Pull request by Pr0methean**
Needed so that Paperclip can be built on modern versions of Maven.

### CODE REVIEW

**Comment by kickash32** [comment]
Java 6 compiles on JDK 11, but not 12. Java 11 is LTS while 12 is not.

**Comment by MiniDigger** [comment]
the alternative would be to "update" the java6 module to java 7.

**Comment by mikroskeem** [comment]
Agreed, rather update this to Java 7.

**Comment by zachbr** [comment]
This was originally added during the MC 1.8 era when everyone and their mom (and their game server hosts) ran Java 6. 

The ecosystem as a whole has changed. MC now requires Java 8, most distros ship with *at least* Java 8, and as I look at our own usage stats I see that there are **zero** people on either Java 6 or Java 7. Everyone is on at least 8 at this point.

I don’t see much reason to try and maintain this helper for Java 6 nor do I see any reason to update it to Java 7.

**Comment by yannicklamprecht** [comment]
From the overall statistic https://bstats.org/global/bukkit we can just drop the versions 6 and 7.
Screenshot 2019-06-16 at 14 57 18

**Comment by zachbr** [comment]
Thanks

**Pull request merged**
